baseurl: https://blog.not-a-kernel-guy.com/
title: Алексей Пахунов
languageCode: ru-ru
disqusShortname: alexeypa
theme: hyde-x

menu:
    main:
        - Name: "Архив"
          Identifier: archive
          URL: post/
        - Name: "Об авторе"
          Identifier: about
          URL: about
        - Name: "Подписаться на RSS канал"
          Identifier: rss
          URL: index.xml
        - Name: "Почтовая рассылка"
          Identifier: email
          URL: https://follow.it/fucjll?action=followPub
params:
    author:
        name: Алексей Пахунов
    customCSS: /css/custom.css
    defaultDescription: Блог про космос, программирование и всякое разное.
    hideReadingTime: true
    highlight: github
    home: "Блог"
    linkedin: https://www.linkedin.com/in/alexpakhunov
    tagline: '... также известный как "Not a kernel guy"'

    archiveLabel: Архив
    nextPageLabel: Старое
    previousPageLabel: Новое

permalinks:
    post: /:year/:month/:day/:slug/

rssLimit: 25

taxonomies:
    tag: "tags"
