baseurl: https://blog.not-a-kernel-guy.com/
title: Алексей Пахунов
languageCode: ru-ru
disqusShortname: alexeypa
theme: hyde-x

author:
    name: Алексей Пахунов

menu:
    main:
        - Name: "Архив"
          Identifier: archive
          URL: post/
        - Name: "Об авторе"
          Identifier: about
          URL: about
        - Name: "Подписаться"
          Identifier: rss
          URL: http://feeds.feedburner.com/not-a-kernel-guy
        - Name: "Рассылка"
          Identifier: email
          URL: https://feedburner.google.com/fb/a/mailverify?uri=not-a-kernel-guy&loc=ru_RU
params:
    customCSS: /css/custom.css
    defaultDescription: Блог про космос, программирование и всякое разное.
    googleAnalytics: UA-1329392-1
    hideReadingTime: true
    highlight: github
    home: "Блог"
    linkedin: https://www.linkedin.com/in/alexpakhunov
    feedburner: http://feeds.feedburner.com/not-a-kernel-guy
    rssLimit: 10
    tagline: '... также известный как "Not a kernel guy"'

    archiveLabel: Архив
    nextPageLabel: Старое
    previousPageLabel: Новое

permalinks:
    post: /:year/:month/:day/:slug/

taxonomies:
    tag: "tags"
